### ISSUE TITLE
make weights optional in st_as_edges

### ISSUE THREAD

**Issue by DHLocke** [JosiahParry/sfweight#16]
first of all, I'm new to posting issues - feedback is welcomed. 

can the weights argument be optional for st_as_edges ? st_knn will create weights that are always the same, by definition. 
https://twitter.com/DextraordinaryH/status/1508855658094944263

**Comment by JosiahParry** [comment]
Moved to https://github.com/JosiahParry/sfdep/issues/6

I should probably delete this repo lol
