### ISSUE TITLE
handle missing values in `categorize_lisa()` 

### ISSUE THREAD

**Issue by JosiahParry** [JosiahParry/sfweight#3]
See https://github.com/JosiahParry/sfweight/issues/2

When there are missing values in a lag the lisa category is returned as `""` when it should be `NA`.

**Comment by kaseyzapatka** [comment]
@JosiahParry, great this worked perfectly. leaving the final product here in case others want to see! thanks so much!

[test_plot.pdf](https://github.com/JosiahParry/sfweight/files/6704356/test_plot.pdf)
